export const othersData = {
  uz: {
    expense: {
      title: "Chiqimlar",
      adding: "Chiqim qo'shish",
      arr: [
        "Sana",
        "Qayerdan chiqim",
        "Chiqim turi",
        "To’lov turi",
        "Valyuta",
        "Summa",
        "Izoh",
      ],
    },
    income: {
      title: "Kirimlar",
      arr: [
        "Sana",
        "Qayerdan chiqim",
        "Kirim turi",
        "To’lov turi",
        "Valyuta",
        "Summa",
        "Izoh",
      ],
    },
    cashRegisters: {
      adding: "Kassa qo’shish",
      title: "Kassalar",
      arr: ["Kassa nomi", "Tegishli bo’lim", "Telefon raqam"],
    },
    confirmation: {
      title: "Pul kirimini tasdiqlash",
      arr: [
        "Sana",
        "Mijoz",
        "Buyurtma kodi",
        "To’lov usuli",
        "Valyuta",
        "Summa",
        "Tasdiqlash",
      ],
    },
    moneyResidue: {
      title: "Pul qoldiqlari",
      arr: [
        "Qayerda",
        "Valyuta",
        "Naqd",
        "Nasiya",
        "Plastik",
        "Plastik",
        "Jami",
      ],
    },
    otherIncome: {
      title: "Boshqa kassaga kelgan kirimlar",
      adding: "To'lov qo’shish",
      arr: ["Summa", "Valyuta", "Sana", "Izoh"],
    },
  },
  ru: {
    expense: {
      title: "Затраты",
      adding: "Добавить расходы",
      arr: [
        "Дата",
        "Откуда я родом",
        "Тип расходов",
        "Тип платежа",
        "Валюта",
        "Сумма",
        "Примечание",
      ],
    },
    income: {
      title: "Квитанции",
      arr: [
        "Дата",
        "Откуда я родом",
        "Тип дохода",
        "Тип платежа",
        "Валюта",
        "Сумма",
        "Примечание",
      ],
    },
    cashRegisters: {
      adding: "Добавить наличные",
      title: "Кассовые аппараты",
      arr: [
        "Название наличных денег",
        "Соответствующий раздел",
        "Номер телефона",
      ],
    },
    confirmation: {
      title: "Подтверждение движения денежных средств",
      arr: [
        "Дата",
        "Покупатель",
        "Код заказа",
        "Метод оплаты",
        "Валюта",
        "Сумма",
        "Подтверждение",
      ],
    },
    moneyResidue: {
      title: "Денежный баланс",
      arr: [
        "Где",
        "Валюта",
        "Наличные",
        "Заем",
        "Пластик",
        "банковский перевод",
        "общий",
      ],
    },
    otherIncome: {
      title: "Поступления от других кассиров",
      adding: "Добавить платеж",
      arr: ["Сумма", "Валюта", "Дата", "Примечание"],
    },
  },
  en: {
    expense: {
      title: "Expenses",
      adding: "Add costs",
      arr: [
        "Date",
        "Where come",
        "Expenditure type",
        "Payment type",
        "Currency",
        "Sum",
        "Comment",
      ],
    },
    income: {
      title: "Receipts",
      arr: [
        "Date",
        "Where come",
        "Income type",
        "Payment type",
        "Currency",
        "Sum",
        "Comment",
      ],
    },
    cashRegisters: {
      adding: "Add cash",
      title: "Cash registers",
      arr: ["Cash name", "Relevant section", "Phone number"],
    },
    confirmation: {
      title: "Confirmation of cash flow",
      arr: [
        "Data",
        "Customer",
        "Order code",
        "Payment method",
        "Currency",
        "Total",
        "Confirmation",
      ],
    },
    moneyResidue: {
      title: "Balance of money",
      arr: [
        "Where",
        "Currency",
        "Cash",
        "Loan",
        "Plastic",
        "Bank transfer",
        "Total",
      ],
    },
    otherIncome: {
      title: "Receipts from other cashiers",
      adding: "Add payment",
      arr: ["Total", "Currency", "Date", "Comment"],
    },
  },
};
