export const loginData = {
  uz: {
    director: {
      login: "Login",
      password: "Parol",
      loginPlaceholder: "Login kiriting",
      passwordPlaceholder: "Parol kiriting",
      button: "Kirish",
      link: "Mijoz sifatida kirish",
      validationUsername: "Usernameni kiriting",
      validationPassword: "Parolni kiriting",
    },
    customerSignIn: {
      title: "Kompaniyangizni qidiring",
      placeholder: "Telefon raqam yoki e-mail kiriting",
      search: "Qidirsh",
      link: "Mijoz sifatida ro’yhatdan o’tish",
      resultTitle: "Sizning kompaniyangiz",
    },
    customerSignUp: {
      companyName: "Kompaniya nomi",
      companyPlaceholder: "Kompaniya nomini kiriting*",
      companyValidation: "Kompaniya nomini kiriting*",
      country: "Mamlakatni tanlang",
      countryValidation: "Mamlakatingizni kiring*",
      phoneNumber: "Telefon raqamingiz",
      phoneNumberValidation: "Telefor raqam kiring*",
      email: "E-mail",
      emailPlaceholder: "E-mail kiriting",
      next: "Davom etish",
    },
    signUpVerify: {
      description:
        "Telefon raqamingizga yuborilgan sms kodni kiriting va tasdiqlang",
      title: "SMS kodni kiriting",
      time: "Qolgan vaqt",
      sendAgain: "Qayta yuborish",
      confirmation: "Tasdiqlash",
    },
  },
  ru: {
    director: {
      login: "Авторизоваться",
      password: "Пароль",
      loginPlaceholder: "Введите свой логин",
      passwordPlaceholder: "Введите пароль",
      button: "Введение",
      link: "Войти как клиент",
      validationUsername: "Введите имя пользователя",
      validationPassword: "Введите пароль",
    },
    customerSignIn: {
      title: "Найдите свою компанию",
      placeholder: "Введите номер телефона или адрес электронной почты",
      search: "Поиск",
      link: "Зарегистрируйтесь как клиент",
      resultTitle: "Твоя компания",
    },
    customerSignUp: {
      companyName: "Название компании",
      companyPlaceholder: "Введите название компании *",
      companyValidation: "Введите название компании",
      country: "Выберите страну",
      countryValidation: "Введите вашу страну *",
      phoneNumber: "Ваш номер телефона",
      phoneNumberValidation: "Введите номер телефона *",
      email: "Эл. почта",
      emailPlaceholder: "Введите адрес электронной почты",
      next: "Продолжать",
    },
    signUpVerify: {
      description:
        "Введите и подтвердите смс-код, отправленный на ваш номер телефона",
      title: "Введите SMS-код",
      time: "Осталось времени",
      sendAgain: "Отправь еще раз",
      confirmation: "Подтверждение",
    },
  },
  en: {
    director: {
      login: "Login",
      password: "Password",
      loginPlaceholder: "Enter username",
      passwordPlaceholder: "Enter password",
      button: "Sign in",
      link: "Login as a client",
      validationUsername: "Fill the username",
      validationPassword: "Fill the password",
    },
    customerSignIn: {
      title: "Your company",
      placeholder: "Enter a phone number or email",
      search: "Search",
      link: "Register as a customer",
      resultTitle: "Your company",
    },
    customerSignUp: {
      companyName: "Company name",
      companyPlaceholder: "Enter company name*",
      companyValidation: "Fill the company name",
      country: "Select country",
      countryValidation: "Fill country*",
      phoneNumber: "Phone number",
      phoneNumberValidation: "Fill the phone number*",
      email: "Email",
      emailPlaceholder: "Enter email",
      next: "Next",
    },
    signUpVerify: {
      description: "Enter and confirm the sms code sent to your phone number",
      title: "Enter the SMS code",
      time: "Time left",
      sendAgain: "Send again",
      confirmation: "Confirmation",
    },
  },
};
